### GET request to example server
GET http://127.0.0.1:8080/data
Accept: application/json

### GET request to example server with async
GET http://127.0.0.1:8080/asyncdata
Accept: application/json
###